<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Demo Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-16T03:51:26</lastRun>
   <mailRecipient>linhnguyen@magrabbit.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>4131b5ca-8a0f-4698-8582-ab64ee6cec8d</testSuiteGuid>
   <testCaseLink>
      <guid>3d9f53ff-0d7f-4a49-89b5-f1b92a9a3018</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Alert</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1705e082-a2b6-4742-ba6e-31388489aa60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5fc7af3-3a75-4689-96bf-31378a5eaef2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ccdbfdf8-e080-485d-b59d-c2c76ef59549</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Text</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0e90f07-22a5-4d36-82cc-11cc10f78d9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcbb3b60-3e81-4fde-b17e-a4397f7b8873</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab0f4be3-8a58-492b-9330-36cc00d14579</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
